# Generated by Django 4.1.4 on 2024-03-19 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_certification_course_remove_userprogress_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='certification',
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
    ]
