# Generated by Django 4.1.4 on 2024-03-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_userprogress_certification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
